// Снимки проекта в студии: npx tsx scripts/project-shots.ts <url> <project.json> <outDir>
// 3D с комнатной стороны, 3D с обратной стороны (камера повёрнута мышью), без фасадов, спереди, план.
import { chromium } from "playwright";
import { readFileSync } from "node:fs";
const [url, file, out] = process.argv.slice(2);
const project = readFileSync(file, "utf8");
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
await page.goto(url);
await page.evaluate((raw) => { localStorage.clear(); localStorage.setItem("module-studio-v3", raw); localStorage.setItem("studio-stage", "bodies"); localStorage.setItem("studio-tip-rmb", "1"); localStorage.setItem("studio-stage-advanced", "1"); }, project);
await page.goto(url);
await page.waitForSelector("canvas");
await page.waitForTimeout(2500);
const shot = async (name: string) => { await page.waitForTimeout(1500); await page.screenshot({ path: `${out}/${name}.png` }); console.log("saved", name); };
const view = async (name: string) => { await page.getByRole("button", { name, exact: true }).click(); await page.waitForTimeout(1200); };
const toggle = async (name: RegExp) => { const b = page.getByRole("button", { name }); if (await b.count()) await b.first().click(); };
const orbit = async (dx: number, dy = 0) => {
  const c = (await page.locator("canvas").first().boundingBox())!;
  const x = c.x + c.width / 2, y = c.y + c.height / 2;
  await page.mouse.move(x, y); await page.mouse.down({ button: "left" });
  for (let i = 1; i <= 20; i++) await page.mouse.move(x + dx * i / 20, y + dy * i / 20);
  await page.mouse.up({ button: "left" });
};
const zoom = async (ticks: number) => { const c = (await page.locator("canvas").first().boundingBox())!; await page.mouse.move(c.x + c.width / 2, c.y + c.height * 0.45); for (let k = 0; k < ticks; k++) { await page.mouse.wheel(0, -200); await page.waitForTimeout(60); } };
const dims = page.getByRole("button", { name: "Показать размеры" });
if (await dims.count() && (await dims.first().getAttribute("aria-pressed")) === "true") await dims.first().click();
await view("3D");
await zoom(Number(process.env.ZOOM ?? 4));
await shot("1-3d-room-side");
await view("Спереди");
await shot("2-front");
await view("План");
await shot("3-plan");
await view("3D");
await toggle(/Свободная камера/);
await orbit(Number(process.env.ORBIT ?? 1500));
await zoom(Number(process.env.ZOOM ?? 4));
await shot("4-3d-other-side");
await toggle(/Скрыть фасады/);
await shot("5-3d-other-side-open");
await view("3D");
await shot("6-3d-room-side-open");
await page.locator(".dock-tabs button", { hasText: "Смета" }).click();
await shot("7-estimate");
await browser.close();
