import {useEffect,useState} from 'react';
import {parseProject,type Project} from './project';
type User={email:string;role:'manager'|'admin'};
type Entry={id:string;name:string;email:string;revision:number;updated:number;archived:number};
async function api(path:string,body?:unknown){const r=await fetch('/api/studio'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','x-studio-request':'1'},...(body===undefined?{}:{body:JSON.stringify(body)})});let data;try{data=await r.json();}catch{throw Error('Сервер кабинета недоступен. Запустите студию с сервером.');}if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Проверьте введённые данные.');return data;}
export function CloudPanel({project,update}:{project:Project;update:(p:Project)=>boolean}){
  const [user,setUser]=useState<User|null>(null),[mode,setMode]=useState(''),[ready,setReady]=useState(false),[email,setEmail]=useState('manager@example.test'),[code,setCode]=useState(''),[sent,setSent]=useState(false),[items,setItems]=useState<Entry[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[all,setAll]=useState(false),[archived,setArchived]=useState(false),[name,setName]=useState(project.modules[0].module.name),[message,setMessage]=useState('');
  const reload=async()=>{const r=await api('/projects?all='+all+'&archived='+archived);setItems(r.items);};
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{let live=true;(async()=>{try{const s=await api('/status');if(!live)return;setMode(s.mode);setReady(s.ready);if(s.mode!=='local-demo')setEmail('');try{const u=await api('/me');if(live)setUser(u);}catch{}}catch(e){if(live)setError((e as Error).message);}})();return()=>{live=false;};},[]);
  useEffect(()=>{if(user)run(reload);},[user,all,archived]);
  async function requestCode(){const r=await api('/auth/code',{email});if(r.demoCode)setUser(await api('/auth/verify',{email,code:r.demoCode}));else setSent(true);}
  async function save(copy:boolean){
    const link=!copy&&project.cloud?.owner===user?.email?project.cloud:undefined,id=link?.id||crypto.randomUUID();
    const r=await api('/projects',{id,name:name.trim()||'Проект',revision:link?.revision||0,data:project});
    update({...project,cloud:{id,revision:r.revision,owner:user!.email}});await reload();setMessage('Проект сохранён. Версия '+r.revision+'.');
  }
  async function load(item:Entry){const r=await api('/projects/'+item.id),p=parseProject(r.data);p.cloud={id:item.id,revision:r.revision,owner:r.email};if(update(p)){setName(item.name);setMessage('Открыт проект «'+item.name+'».');}}
  return <div className="cloud-panel"><p className="field-note">{mode==='local-demo'?'Сейчас кабинет работает на этом компьютере. Демо-профили общие; письма не отправляются. Это ещё не размещение в облаке.':'Проекты сотрудников хранятся на сервере. Менеджер видит свои проекты, администратор — все.'}</p>{error&&<p role="alert" className="cloud-error">{error}</p>}{message&&<p role="status" className="cloud-success">{message}</p>}
  {!user?<div className="cloud-login">{!ready&&mode&&<p>Для входа настройте серверную почту и список сотрудников.</p>}<label className="hardware-field">{mode==='local-demo'?'Проверочный профиль':'Рабочая почта'}{mode==='local-demo'?<select aria-label="Профиль кабинета" value={email} onChange={e=>setEmail(e.target.value)}><option value="manager@example.test">Менеджер</option><option value="manager2@example.test">Другой менеджер</option><option value="admin@example.test">Администратор</option></select>:<input aria-label="Почта кабинета" type="email" value={email} onChange={e=>setEmail(e.target.value)}/>}</label><button className="primary" disabled={busy||!ready} onClick={()=>run(requestCode)}>{mode==='local-demo'?'Войти в локальный кабинет':'Получить код'}</button>{sent&&<><label className="hardware-field">Код из письма<input aria-label="Код входа" value={code} onChange={e=>setCode(e.target.value)} maxLength={6}/></label><button className="primary" disabled={busy} onClick={()=>run(async()=>setUser(await api('/auth/verify',{email,code})))}>Войти</button></>}</div>:<>
    <div className="cloud-user"><span>{user.role==='admin'?'Администратор':'Менеджер'} · {user.email}</span><button onClick={()=>run(async()=>{await api('/logout',{});setUser(null);setItems([]);setAll(false);})}>Выйти</button></div>
    <div className="cloud-save"><label className="hardware-field">Название проекта<input aria-label="Название сохраняемого проекта" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><button className="primary" disabled={busy} onClick={()=>run(()=>save(false))}>Сохранить проект</button><button className="outline" disabled={busy} onClick={()=>run(()=>save(true))}>Сохранить копию</button></div>
    <div className="cloud-filters">{user.role==='admin'&&<label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Все сотрудники</label>}<label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Архив</label></div>
    {!items.length&&<p className="field-note">Здесь пока нет проектов.</p>}{items.map(item=><article className="cloud-project" key={item.id}><div><strong>{item.name}</strong><small>{item.email} · версия {item.revision} · {new Date(item.updated*1000).toLocaleString('ru-RU')}</small></div><button className="outline" disabled={busy} onClick={()=>run(()=>load(item))}>Открыть проект</button>{item.email===user.email&&<button className="text-action" disabled={busy} onClick={()=>run(async()=>{await api('/projects/'+item.id+'/archive?archived='+!archived,{});await reload();})}>{archived?'Восстановить':'В архив'}</button>}</article>)}
  </>}</div>;
}
