import {useState,useMemo,useEffect,useRef} from 'react';
import {Scene,type View} from './Scene';
import {parseProject,type Project} from './project';
import {parts} from './model';
import {catalog} from './catalog';
import {CORNER_DEFAULT,CORNER_NOTES,CORNER_STORAGE,cornerProject,parseCorner,parametersFromCornerProject,type CornerParameters} from './cornerWardrobe';
import {cutting,cutCSV,cuttingHTML,sheetSVG,mm} from './cornerCutting';
import './corner-studio.css';

const KEY=CORNER_STORAGE;
function load(project?:Project){if(project)return parametersFromCornerProject(project);try{const s=localStorage.getItem(KEY);return s?parseCorner(JSON.parse(s)):CORNER_DEFAULT;}catch{return CORNER_DEFAULT;}}
function save(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const fields:[keyof CornerParameters,string,number,number][]=[['arm','Обе стороны по стенам',950,1400],['height','Общая высота',2200,2800],['sideDepth','Глубина боковин',400,650],['upperClear','Просвет антресоли',300,550],['middleClear','Средний проём',200,450],['bayWidth','Ширина бокового блока',300,400],['bayDepth','Глубина бокового блока',300,450],['drawerHeight','Высота коробов ящиков',140,230]];
export default function CornerStudio({initialProject}:{initialProject?:Project}){
 const [history,setHistory]=useState<CornerParameters[]>(()=>[load(initialProject)]),[cursor,setCursor]=useState(0),p=history[cursor];
 const project=useMemo(()=>cornerProject(p),[p]),cut=useMemo(()=>cutting(project),[project]);
 const [tab,setTab]=useState<'model'|'cuts'|'parts'>('model'),[view,setView]=useState<View>('iso'),[open,setOpen]=useState(true),[transparent,setTransparent]=useState(false),[hide,setHide]=useState(false),[fit,setFit]=useState(0),[error,setError]=useState(''),[notes,setNotes]=useState(false),[active,setActive]=useState('corner-main'),[selected,setSelected]=useState<string>(),[drawer,setDrawer]=useState<{sid:string;index:number}>();
 const file=useRef<HTMLInputElement>(null),capture=useRef<(()=>string)|undefined>(undefined);
 const m=project.modules.find(a=>a.id===active)!.module,selectedPart=parts(m).find(d=>d.id===selected);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(p));}catch{setError('Автосохранение недоступно. Скачайте проект кнопкой вверху.');}},[p]);
 function commit(next:CornerParameters){try{const q=parseCorner(next);cutting(cornerProject(q));setHistory(h=>[...h.slice(0,cursor+1),q]);setCursor(cursor+1);setError('');setSelected(undefined);}catch(e){setError((e as Error).message);}}
 const change=(key:keyof CornerParameters,value:unknown)=>commit({...p,[key]:value});
 const noop=()=>{},no=()=>false,reason=()=> 'Измените параметры углового шкафа слева.';
 const boards=cut.sheets.filter(s=>s.material==='ЛДСП'),hdf=cut.sheets.filter(s=>s.material==='ХДФ');
 const inner=p.height-p.upperClear-32-p.middleClear-32-80;
 return <div className="corner-app">
  <header className="corner-head"><div><a href="./">← Студия шкафов</a><h1>Угловой шкаф</h1><p>По вашему эскизу · 05.10.2026</p></div><div className="corner-actions"><button disabled={!cursor} onClick={()=>{setCursor(cursor-1);setError('');}}>Отменить</button><button disabled={cursor===history.length-1} onClick={()=>{setCursor(cursor+1);setError('');}}>Повторить</button><button onClick={()=>file.current?.click()}>Открыть проект</button><button onClick={()=>save('corner-1050-project.json',JSON.stringify(project,null,2))}>Скачать проект</button><button onClick={()=>setNotes(!notes)} aria-expanded={notes}>Допущения</button></div></header>
  <input ref={file} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>2e6)throw Error('Слишком большой файл.');commit(parametersFromCornerProject(parseProject(JSON.parse(await f.text()))));}catch(e){setError((e as Error).message);}}}/>
  <div className="corner-status"><span>ПРЕДВАРИТЕЛЬНЫЙ РАСЧЁТ</span> Материалы и фурнитура пока не подтверждены. Нижний просвет {inner} мм; на исходной схеме указан 1588 мм.</div>
  {error&&<div className="corner-error" role="alert">{error}<button onClick={()=>setError('')}>Закрыть</button></div>}
  <div className="corner-layout"><aside className="corner-panel"><h2>Конструкция</h2><p className="corner-muted">Размеры в миллиметрах. Нажмите Enter или выйдите из поля.</p>
   {fields.map(([key,label,min,max])=><label key={key}>{label}<input aria-label={label} key={key+String(p[key])} type="number" min={min} max={max} step="1" defaultValue={Number(p[key])} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} onBlur={e=>{if(Number(e.target.value)!==p[key]){change(key,Number(e.target.value));e.target.value=String(p[key]);}}}/></label>)}
   <h2>Материалы и ящики</h2><label>Корпус и полки<select value={p.decor} onChange={e=>change('decor',e.target.value)}>{catalog.map(d=><option key={d.n}>{d.n}</option>)}</select></label><label>Фасады<select value={p.facadeDecor} onChange={e=>change('facadeDecor',e.target.value)}>{catalog.map(d=><option key={d.n}>{d.n}</option>)}</select></label>
   <label>Задние стенки<select value={p.back} onChange={e=>change('back',e.target.value)}><option value="hdf">ХДФ 3 мм · накладные</option><option value="none">Без задних стенок</option></select></label>
   <label>Направляющие<select value={p.slide} onChange={e=>change('slide',e.target.value)}><option value="ball">GTV · шариковые · зазор 13 мм</option><option value="gtv0fpo">GTV 0FPO · скрытые · ЛДСП 16</option></select></label><label>Длина направляющих<select value={p.slideLength} onChange={e=>change('slideLength',Number(e.target.value))}>{[250,300,350,400].map(n=><option key={n} value={n}>{n} мм</option>)}</select></label><p className="corner-muted">Дно всех шести ящиков — ЛДСП 16 мм. Смена направляющих меняет детали коробов.</p><button className="corner-reset" onClick={()=>commit(CORNER_DEFAULT)}>Вернуть исходный эскиз</button>
  </aside><main className="corner-main"><nav className="corner-tabs" aria-label="Разделы проекта">{([['model','3D-модель'],['cuts','Раскрой листов'],['parts','Деталировка']] as const).map(([k,label])=><button key={k} aria-pressed={tab===k} onClick={()=>setTab(k)}>{label}</button>)}<div className="corner-totals">{boards.length} ЛДСП + {hdf.length} ХДФ <small>{cut.pieces.length} деталей</small></div></nav>
   {tab==='model'&&<><div className="corner-tools">{(['iso','front','side','top'] as View[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{{iso:'Объём',front:'Спереди',side:'Сбоку',top:'План сверху'}[v]}</button>)}<button onClick={()=>setFit(n=>n+1)}>Вписать</button><button onClick={()=>{const url=capture.current?.();if(url){const a=document.createElement('a');a.href=url;a.download='corner-'+view+'.png';a.click();}}}>Снимок PNG</button></div>
    <div className="corner-scene"><Scene isoDirection={[1,1]} arrangement={project.modules} module={m} activeId={active} mode="select" moveAll={false} snap={(_,q)=>q} onMoveModule={no} moveProblem={reason} onMoveDivider={no} dividerProblem={reason} partProblem={reason} onMovePart={no} onDropItem={no} onTransfer={no} captureReady={fn=>{capture.current=fn;}} onObstacleSelect={noop} onModuleSelect={id=>{setActive(id);setDrawer(undefined);setSelected(undefined);}} transparent={transparent} hideFacades={hide} onDimension={noop} onGap={noop} onPartSelect={(_,id,mid)=>{if(mid)setActive(mid);setSelected(id);}} selected="front" selectedPart={selected} onSelect={noop} view={view} fit={fit} openDoors={open} exploded={false} dimensions={false} presentation={false} drawerPreview={drawer}/></div>
    <div className="corner-toggles"><label><input type="checkbox" checked={open} onChange={e=>{setOpen(e.target.checked);setDrawer(undefined);}}/>Открыть двери</label><label><input type="checkbox" checked={hide} onChange={e=>setHide(e.target.checked)}/>Скрыть фасады</label><label><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)}/>Прозрачный корпус</label></div>
    <div className="corner-drawers"><span>Проверить ящик:</span>{['left','right'].map(side=><button key={side} aria-pressed={drawer?.sid===side} onClick={()=>{setActive('corner-main');setOpen(true);setDrawer(drawer?.sid===side?undefined:{sid:side,index:0});}}>{side==='left'?'Левый':'Правый'} нижний</button>)}<small>Показано условное открывание; петли угловых фасадов требуют подбора.</small></div>
    <div className="corner-caption"><strong>{p.arm} × {p.arm} × {p.height} мм</strong><span>Два корпуса · четыре двери · шесть ящиков</span><span>Вращение мышью · приближение колесом · клик по детали</span></div>{selectedPart&&<p className="corner-selection">{selectedPart.name} · {mm(selectedPart.length)} × {mm(selectedPart.width)} × {selectedPart.thickness} мм</p>}
   </>}
   {tab==='cuts'&&<div className="corner-output"><div className="corner-output-head"><div><h2>Карты размещения заготовок</h2><p>ЛДСП 2750 × 1830 · ХДФ 2800 × 2070 · поле и промежуток по 10 мм</p></div><button onClick={()=>save('corner-cutting.html',cuttingHTML(cut,CORNER_NOTES),'text/html;charset=utf-8')}>Скачать карты / печать PDF</button></div><p>Кромка уже вычтена. Пятиугольники и трапеция показаны внутри заготовок; их внутренние обрезки не переиспользуются. Карта не задаёт последовательность резов. Цвета: корпус — бежевый, полки — зелёный, ящики — голубой, двери — сиреневый.</p><div className="corner-sheets">{cut.sheets.map((s,i)=><article key={i}><h3>Лист {i+1} · {s.material} {s.thickness} мм</h3><p>{s.decor} · {s.items.length} деталей</p><div dangerouslySetInnerHTML={{__html:sheetSVG(s,i)}}/><details><summary>Размеры деталей этого листа</summary><table><tbody>{s.items.map(a=><tr key={a.id}><th>{a.piece.code}</th><td>{a.piece.part.name}</td><td>{mm(a.piece.length)} × {mm(a.piece.width)}</td></tr>)}</tbody></table></details></article>)}</div></div>}
   {tab==='parts'&&<div className="corner-output"><div className="corner-output-head"><h2>{cut.pieces.length} деталей</h2><button onClick={()=>save('corner-parts.csv',cutCSV(cut),'text/csv;charset=utf-8')}>Скачать CSV для Excel</button></div><p>Готовый размер включает кромку. Заготовка — размер до кромления. У фигурных деталей здесь указан габарит заготовки, контуры находятся в картах раскроя.</p><table className="corner-parts"><thead><tr><th>Код</th><th>Деталь</th><th>Готовая, мм</th><th>Заготовка, мм</th><th>Лист</th></tr></thead><tbody>{cut.pieces.map(a=><tr key={a.key}><td>{a.code}</td><td>{a.part.name}<small>{a.module} · {a.part.material==='hdf'?'ХДФ':a.part.decor}</small></td><td>{mm(a.part.length)} × {mm(a.part.width)} × {a.part.thickness}</td><td>{mm(a.length)} × {mm(a.width)}</td><td>{cut.sheets.findIndex(s=>s.items.some(b=>b.id===a.key))+1}</td></tr>)}</tbody></table></div>}
  </main></div>
  {notes&&<section className="corner-notes"><h2>Источник и принятые допущения</h2><p>Исходные условия ниже относятся к первоначальному эскизу. Текущие размеры и материалы находятся в параметрах и ведомости.</p><ol>{CORNER_NOTES.map(n=><li key={n}>{n}</li>)}</ol></section>}
  <footer className="corner-footer">Расчёт по модели · кромка без запаса: 0,4 мм — {mm(cut.edge04)} м; 2 мм — {mm(cut.edge2)} м · технологическая проверка перед производством обязательна</footer>
 </div>;
}
