import {useEffect,useRef,useState} from 'react';
import {parseModule,type Module} from './model';
import {libraryFile,parseLibraryFile,type LibraryEntry as Entry} from './moduleLibraryFile';
const KEY='module-studio-library-v1';
export function ModuleLibrary({module,insert}:{module:Module;insert:(m:Module)=>boolean}){
  const live=useRef(false),revision=useRef(0);
  useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
  const input=useRef<HTMLInputElement>(null);
  const [previous,setPrevious]=useState<Entry[]|null>(null);
  const [error,setError]=useState(''),[name,setName]=useState(module.name),[items,setItems]=useState<Entry[]>(()=>{try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(raw))return [];return raw.slice(0,30).flatMap(a=>{try{return typeof a.id==='string'&&typeof a.name==='string'?[{id:a.id,name:a.name.slice(0,80),module:parseModule(a.module)}]:[];}catch{return [];}});}catch{return [];}});
  function save(next:Entry[],remember=true){try{localStorage.setItem(KEY,JSON.stringify(next));revision.current++;if(remember)setPrevious(items);setItems(next);setError('');return true;}catch{setError('Не удалось записать библиотеку. Проверьте свободное место в браузере.');return false;}}
  function exportFile(){const url=URL.createObjectURL(new Blob([libraryFile(items)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Библиотека модулей.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function importFile(file:File){const before=revision.current;try{if(file.size>2_000_000)throw Error('Файл библиотеки слишком большой (не более 2 МБ).');const text=await file.text();if(!live.current)return;if(before!==revision.current)throw Error('Библиотека изменилась во время чтения файла. Загрузите его ещё раз.');const incoming=parseLibraryFile(JSON.parse(text));if(items.length+incoming.length>30)throw Error('Вместе с импортом будет больше 30 шаблонов. Освободите место или используйте другую библиотеку.');save([...items,...incoming]);}catch(e){if(live.current)setError((e as Error).message);}}
  return <div className="module-library"><p className="field-note">Личная библиотека в этом браузере. Сохраняет размеры, материалы и наполнение. Каждый вставленный корпус редактируется независимо.</p>{error&&<p role="alert">{error}</p>}<label className="hardware-field">Название шаблона<input aria-label="Название шаблона модуля" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={!name.trim()||items.length>=30} onClick={()=>save([...items,{id:crypto.randomUUID(),name:name.trim(),module:structuredClone(module)}])}>Сохранить выбранный модуль</button><p className="field-note">{items.length} из 30 шаблонов. Импорт добавляет шаблоны к существующим; одинаковые названия допускаются.</p><div className="cloud-filters"><button className="outline" disabled={!items.length} onClick={exportFile}>Скачать библиотеку</button><button className="outline" onClick={()=>input.current?.click()}>Загрузить библиотеку</button><button className="text-action" disabled={!previous} onClick={()=>{if(previous&&save(previous,false))setPrevious(null);}}>Отменить изменение библиотеки</button></div><input hidden ref={input} type="file" accept=".json,application/json" aria-label="Файл библиотеки модулей" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importFile(file);}}/>{items.map(a=><article className="cloud-project" key={a.id}><div><strong>{a.name}</strong><small>{a.module.width} × {a.module.height} × {a.module.depth} мм · {a.module.decor}</small><small>Полок {a.module.sections.reduce((n,s)=>n+s.shelves.length,0)} · ящиков {a.module.sections.reduce((n,s)=>n+s.drawers,0)}</small></div><button className="outline" onClick={()=>insert({...structuredClone(a.module),name:a.name})}>Вставить модуль</button><button className="text-action" onClick={()=>save(items.filter(b=>b.id!==a.id))}>Убрать из библиотеки</button></article>)}</div>;
}
