import {useState} from 'react';
import {parseModule,type Module} from './model';
type Entry={id:string;name:string;module:Module};
const KEY='module-studio-library-v1';
export function ModuleLibrary({module,insert}:{module:Module;insert:(m:Module)=>boolean}){
  const [error,setError]=useState(''),[name,setName]=useState(module.name),[items,setItems]=useState<Entry[]>(()=>{try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(raw))return [];return raw.slice(0,30).flatMap(a=>{try{return typeof a.id==='string'&&typeof a.name==='string'?[{id:a.id,name:a.name.slice(0,80),module:parseModule(a.module)}]:[];}catch{return [];}});}catch{return [];}});
  function save(next:Entry[]){try{localStorage.setItem(KEY,JSON.stringify(next));setItems(next);setError('');}catch{setError('Не удалось записать библиотеку. Проверьте свободное место в браузере.');}}
  return <div className="module-library"><p className="field-note">Личная библиотека в этом браузере. Сохраняет размеры, материалы и наполнение. Каждый вставленный корпус редактируется независимо.</p>{error&&<p role="alert">{error}</p>}<label className="hardware-field">Название шаблона<input aria-label="Название шаблона модуля" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={!name.trim()||items.length>=30} onClick={()=>save([...items,{id:crypto.randomUUID(),name:name.trim(),module:structuredClone(module)}])}>Сохранить выбранный модуль</button><p className="field-note">{items.length} из 30 шаблонов. Для переноса на другой компьютер сохраните проект файлом.</p>{items.map(a=><article className="cloud-project" key={a.id}><div><strong>{a.name}</strong><small>{a.module.width} × {a.module.height} × {a.module.depth} мм · {a.module.decor}</small><small>Полок {a.module.sections.reduce((n,s)=>n+s.shelves.length,0)} · ящиков {a.module.sections.reduce((n,s)=>n+s.drawers,0)}</small></div><button className="outline" onClick={()=>insert({...structuredClone(a.module),name:a.name})}>Вставить модуль</button><button className="text-action" onClick={()=>save(items.filter(b=>b.id!==a.id))}>Убрать из библиотеки</button></article>)}</div>;
}
