import {useEffect,useRef} from 'react';
import {id} from './model';
import type {Room,RoomObstacle} from './project';
const names={column:'Колонна',beam:'Балка',radiator:'Радиатор'};
export function RoomObstacles({room,selected,onSelect,onChange}:{room:Room;selected?:string;onSelect:(id:string)=>void;onChange:(r:Room)=>boolean}){
 const cards=useRef(new Map<string,HTMLDivElement>());useEffect(()=>{if(selected)cards.current.get(selected)?.scrollIntoView({block:'nearest'});},[selected]);
 function patch(o:RoomObstacle,change:Partial<RoomObstacle>){return onChange({...room,obstacles:(room.obstacles||[]).map(a=>a.id===o.id?{...a,...change}:a)});}
 function add(type:RoomObstacle['type']){const width=Math.min(type==='radiator'?800:type==='beam'?1200:300,room.width),depth=Math.min(type==='radiator'?150:300,room.depth),height=type==='column'?room.height:Math.min(type==='beam'?300:600,room.height),o:RoomObstacle={id:id(),type,name:names[type],x:Math.round((room.width-width)/2),z:0,y:type==='beam'?room.height-height:type==='radiator'?Math.min(100,room.height-height):0,width,depth,height};if(onChange({...room,obstacles:[...(room.obstacles||[]),o]}))onSelect(o.id);}
 return <div className="room-openings"><h3>Объекты замера</h3><p className="field-note">Схематичные габариты колонн, балок и радиаторов. Выбор — на плане или в 3D с включённым помещением; перемещение — на плане. Пересечения с мебелью отмечаются подсказками; монтажные и тепловые зазоры задайте по замеру и техничке.</p><div className="room-add">{(['column','beam','radiator'] as const).map(type=><button key={type} disabled={(room.obstacles?.length??0)>=30} onClick={()=>add(type)}>{names[type]}</button>)}</div>
 {(room.obstacles||[]).map((o,i)=><div className={'opening-card'+(selected===o.id?' selected':'')} key={o.id} ref={node=>{if(node)cards.current.set(o.id,node);else cards.current.delete(o.id);}} onFocus={()=>onSelect(o.id)}><header><button className="opening-title" onClick={()=>onSelect(o.id)}>П{i+1} · {names[o.type]}</button><button aria-label={'Удалить объект замера '+(i+1)} onClick={()=>onChange({...room,obstacles:room.obstacles?.filter(a=>a.id!==o.id)})}>×</button></header><input aria-label={'Название объекта '+(i+1)} key={o.name} defaultValue={o.name} maxLength={80} onBlur={e=>{if(!patch(o,{name:e.target.value.trim()}))e.target.value=o.name;}}/>
 {(['width','depth','height','x','z','y'] as const).map(k=><label key={k}>{{width:'Ширина',depth:'Глубина',height:'Высота',x:'От левой стены',z:'От задней стены',y:'От пола'}[k]}<input type="number" aria-label={{width:'Ширина',depth:'Глубина',height:'Высота',x:'Слева',z:'Сзади',y:'Снизу'}[k]+' объекта '+(i+1)} key={o[k]} defaultValue={o[k]} onBlur={e=>{if(!patch(o,{[k]:Number(e.target.value)}))e.target.value=String(o[k]);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>мм</span></label>)}</div>)}
 </div>;
}
