import {useEffect,useRef} from 'react';
import {id} from './model';
import type {Room,RoomObstacle} from './project';
const names={column:'Колонна',beam:'Балка',radiator:'Радиатор',fridge:'Холодильник',washer:'Стиральная машина',stove:'Плита'};
export function RoomObstacles({room,selected,onSelect,onChange}:{room:Room;selected?:string;onSelect:(id:string)=>void;onChange:(r:Room)=>boolean}){
 const cards=useRef(new Map<string,HTMLDivElement>());useEffect(()=>{if(selected)cards.current.get(selected)?.scrollIntoView({block:'nearest'});},[selected]);
 function patch(o:RoomObstacle,change:Partial<RoomObstacle>){return onChange({...room,obstacles:(room.obstacles||[]).map(a=>a.id===o.id?{...a,...change}:a)});}
 function add(type:RoomObstacle['type']){const size={column:[300,300,room.height],beam:[1200,300,300],radiator:[800,150,600],fridge:[600,650,1850],washer:[600,600,850],stove:[600,600,850]}[type];const width=Math.min(size[0],room.width),depth=Math.min(size[1],room.depth),height=Math.min(size[2],room.height),o:RoomObstacle={id:id(),type,name:names[type],x:Math.round((room.width-width)/2),z:0,y:type==='beam'?room.height-height:type==='radiator'?Math.min(100,room.height-height):0,width,depth,height};if(onChange({...room,obstacles:[...(room.obstacles||[]),o]}))onSelect(o.id);}
 return <div className="room-openings"><h3>Объекты в комнате</h3><p className="field-note">Колонны, балки, техника (холодильник, стиральная машина, плита) — как раздел «Разное» скрипта Базиса. Выбор — на плане или в 3D; перемещение — на плане. Пересечения с мебелью отмечаются подсказками.</p><div className="room-add">{(['column','beam','radiator','fridge','washer','stove'] as const).map(type=><button key={type} disabled={(room.obstacles?.length??0)>=30} onClick={()=>add(type)}>{names[type]}</button>)}</div>
 {(room.obstacles||[]).map((o,i)=><div className={'opening-card'+(selected===o.id?' selected':'')} key={o.id} ref={node=>{if(node)cards.current.set(o.id,node);else cards.current.delete(o.id);}} onFocus={()=>onSelect(o.id)}><header><button className="opening-title" onClick={()=>onSelect(o.id)}>П{i+1} · {names[o.type]}</button><button aria-label={'Удалить объект замера '+(i+1)} onClick={()=>onChange({...room,obstacles:room.obstacles?.filter(a=>a.id!==o.id)})}>×</button></header><input aria-label={'Название объекта '+(i+1)} key={o.name} defaultValue={o.name} maxLength={80} onBlur={e=>{if(!patch(o,{name:e.target.value.trim()}))e.target.value=o.name;}}/>
 {(['width','depth','height','x','z','y'] as const).map(k=><label key={k}>{{width:'Ширина',depth:'Глубина',height:'Высота',x:'От левой стены',z:'От задней стены',y:'От пола'}[k]}<input type="number" aria-label={{width:'Ширина',depth:'Глубина',height:'Высота',x:'Слева',z:'Сзади',y:'Снизу'}[k]+' объекта '+(i+1)} key={o[k]} defaultValue={o[k]} onBlur={e=>{if(!patch(o,{[k]:Number(e.target.value)}))e.target.value=String(o[k]);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>мм</span></label>)}</div>)}
 </div>;
}
